---
# Exploring community.vmware collection
#
# Example module used:
# https://github.com/ansible-collections/community.vmware/blob/main/docs/community.vmware.vmware_guest_module.rst
- name: Launching a VM with community.vmware
  connection: local   # python3 -m pip install pyvmomi
  hosts: localhost    # no inventory, we only have a single instance to communicate with
  gather_facts: no

  vars:
      vcenter_hostname: 192.168.2.83
      vcenter_username: admin@vsphere.local
      vcenter_password: Password321  # secure in ansible vault or with a lookup() plugin
      esxi_hostname: esxi01-alta3.demo.local

  tasks:
  
      - name: Create a vm on given ESXi host
        community.vmware.vmware_guest:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            folder: 'vm'
            name: test_vm_0001  # name of the vm to be launched
            state: poweredon
            guest_id: centos64Guest
            # This is hostname of particular ESXi server on which user wants VM to be deployed
            esxi_hostname: "{{ esxi_hostname }}"
            disk:
            - size_gb: 10
              type: thin
              datastore: datastore1
            hardware:
              memory_mb: 512
              num_cpus: 4
              scsi: paravirtual
            networks:
            - name: VM Network
              mac: aa:bb:dd:aa:00:14
              ip: 10.10.10.100
              netmask: 255.255.255.0
              device_type: vmxnet3
            wait_for_ip_address: true
            wait_for_ip_address_timeout: 600
        register: deploy_vm
      
      - name: results of launched vm
        debug:
            var: deploy_vm

